packages:
  - apps/**
  - packages/**

catalog:
  '@axe-core/playwright': 4.13.0
  '@nuxt/test-utils': 4.3.2
  dotenv: 18.0.4
  nuxt: 4.5.2
  typescript: 6.0.3
  vue-tsc: 3.3.11

minimumReleaseAge: 4320 # 3 days
autoInstallPeers: true
shamefullyHoist: true

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true
  vue-demi: true
