packages:
  - apps/**
  - packages/**

catalog:
  '@axe-core/playwright': 4.11.0
  '@nuxt/test-utils': ^3.19.1
  '@vitest/coverage-v8': 3.2.4
  dotenv: 17.2.3
  nuxt: 4.1.3
  typescript: 5.9.3
  vue-tsc: 3.1.2
