packages:
  - apps/**
  - packages/**

catalog:
  '@axe-core/playwright': 4.11.0
  '@nuxt/test-utils': 3.21.0
  dotenv: 17.2.3
  nuxt: 4.2.2
  typescript: 5.9.3
  vue-tsc: 3.2.1

minimumReleaseAge: 4320 # 3 days
autoInstallPeers: true
shamefullyHoist: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
  - vue-demi
