packages:
  - 'apps/**'
  - 'packages/**'

catalog:
  '@axe-core/playwright': ^4.10.2
  '@nuxtjs/i18n': ^9.5.5
  '@nuxt/test-utils': ^3.19.1
  nuxt: 4.0.0
  typescript: ^5.8.3
  vue: "latest"
  vue-router: "^4.5.1"
  vue-tsc: ^3.0.2
