packages:
  - apps/**
  - packages/**

catalog:
  '@axe-core/playwright': ^4.10.2
  '@nuxt/test-utils': ^3.19.1
  '@vitest/coverage-v8': ^3.2.4
  dotenv: ^17.2.1
  nuxt: ^4.1.0
  typescript: ^5.8.3
  vue-tsc: ^3.0.4
